-- Seed content for CISSP Domain 1: Security and Risk Management
-- Section + 3 focused lessons + mini-exam question banks (10 questions each).
-- Run in Supabase SQL Editor. Safe to re-run (uses delete-then-insert per lesson slug).

-- Remove the old flat placeholder lesson that predates the section model.
delete from progress where lesson_id in (
  select id from lessons
  where course_id = (select id from courses where slug = 'cissp')
  and section_id is null
);
delete from lessons
where course_id = (select id from courses where slug = 'cissp')
and section_id is null;

-- 1. Section
insert into sections (course_id, slug, title, description, order_index, exam_weight_percent)
select id, 'security-and-risk-management', 'Domain 1: Security and Risk Management',
  'Governance, compliance, risk management, and the foundational principles security professionals build everything else on.',
  1, 16
from courses where slug = 'cissp'
on conflict (course_id, slug) do update set
  title = excluded.title, description = excluded.description,
  order_index = excluded.order_index, exam_weight_percent = excluded.exam_weight_percent;

-- 2. Lessons + questions

-- Lesson 1: The CIA Triad
delete from progress where lesson_id in (select id from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'The CIA Triad');
delete from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'The CIA Triad';
with new_lesson as (
  insert into lessons (course_id, section_id, title, order_index, estimated_minutes, content_blocks)
  select c.id, s.id, 'The CIA Triad', 1, 8, '[{"type": "heading", "text": "Why the CIA Triad Matters"}, {"type": "paragraph", "text": "Nearly every security control you''ll ever evaluate exists to protect one (or more) of three properties: confidentiality, integrity, and availability. When a CISSP exam question asks \"what security principle was violated,\" it''s almost always asking you to identify which of these three."}, {"type": "key_term", "term": "Confidentiality", "definition": "Preventing unauthorized disclosure of information. Enforced through principles like need-to-know and least privilege, and controls like encryption and role-based access."}, {"type": "key_term", "term": "Integrity", "definition": "Protecting data and systems from unauthorized modification, ensuring information stays accurate and trustworthy. Enforced through controls like change management, hashing, and digital signatures."}, {"type": "key_term", "term": "Availability", "definition": "Ensuring authorized users can access systems and data when they need to. Enforced through controls like redundancy, backups, and disaster recovery planning."}, {"type": "paragraph", "text": "Two related properties extend the triad and show up regularly on the exam: authenticity (proving an asset or identity is genuine) and non-repudiation (preventing someone from credibly denying an action they took, typically via audit logs and digital signatures)."}, {"type": "list", "style": "bullet", "items": ["A stolen laptop full of unencrypted customer records is a confidentiality failure.", "An attacker altering financial transaction data in transit is an integrity failure.", "A DDoS attack that takes a website offline is an availability failure.", "A forged email claiming to be from the CEO is an authenticity failure.", "A user denying they approved a wire transfer that logs show they approved is a non-repudiation failure."]}, {"type": "callout", "variant": "tip", "text": "Exam tip: scenario questions describe an incident and ask which principle was violated. Read for the *effect* of the attack (data exposed? data changed? system down?), not the attack method itself."}]'::jsonb
  from courses c
  join sections s on s.course_id = c.id and s.slug = 'security-and-risk-management'
  where c.slug = 'cissp'
  returning id
)
insert into questions (lesson_id, question_text, question_type, choices, correct_choice_ids, explanation)
select id, 'An attacker intercepts a database backup file and reads customer social security numbers stored in plain text. Which CIA triad principle was primarily violated?', 'single', '[{"id": "a", "text": "Confidentiality"}, {"id": "b", "text": "Integrity"}, {"id": "c", "text": "Availability"}, {"id": "d", "text": "Non-repudiation"}]'::jsonb, '["a"]'::jsonb, 'Reading data that should have been restricted is unauthorized disclosure, which is a confidentiality failure.' from new_lesson
union all
select id, 'A ransomware attack encrypts a hospital''s patient record system, and staff cannot access patient charts for 18 hours. Which principle was primarily violated?', 'single', '[{"id": "a", "text": "Confidentiality"}, {"id": "b", "text": "Integrity"}, {"id": "c", "text": "Availability"}, {"id": "d", "text": "Authenticity"}]'::jsonb, '["c"]'::jsonb, 'Authorized users being unable to access systems/data when needed is an availability failure.' from new_lesson
union all
select id, 'An employee discovers that a competitor''s price list was altered in the shared drive so figures no longer match the original, approved version. Which principle was violated?', 'single', '[{"id": "a", "text": "Availability"}, {"id": "b", "text": "Integrity"}, {"id": "c", "text": "Confidentiality"}, {"id": "d", "text": "Non-repudiation"}]'::jsonb, '["b"]'::jsonb, 'Unauthorized modification of data, making it no longer accurate/trustworthy, is an integrity failure.' from new_lesson
union all
select id, 'Which of the following are controls primarily associated with protecting confidentiality? (Select two.)', 'multi', '[{"id": "a", "text": "Encryption of data at rest"}, {"id": "b", "text": "Role-based access control"}, {"id": "c", "text": "Redundant power supplies"}, {"id": "d", "text": "Load balancing across servers"}]'::jsonb, '["a", "b"]'::jsonb, 'Encryption and role-based access control both restrict who can view data, protecting confidentiality. Redundant power and load balancing protect availability.' from new_lesson
union all
select id, 'Which security property is most directly enforced by digital signatures used to prove a specific user submitted a specific transaction?', 'single', '[{"id": "a", "text": "Availability"}, {"id": "b", "text": "Non-repudiation"}, {"id": "c", "text": "Confidentiality"}, {"id": "d", "text": "Least privilege"}]'::jsonb, '["b"]'::jsonb, 'Non-repudiation prevents someone from credibly denying an action they took; digital signatures and audit logs are the classic supporting controls.' from new_lesson
union all
select id, 'A phishing email is crafted to look like it was sent from the company''s CFO. Which extended triad property does this attack primarily target?', 'single', '[{"id": "a", "text": "Integrity"}, {"id": "b", "text": "Availability"}, {"id": "c", "text": "Authenticity"}, {"id": "d", "text": "Confidentiality"}]'::jsonb, '["c"]'::jsonb, 'Authenticity is about proving an asset or identity is genuine; a spoofed sender identity is an authenticity attack.' from new_lesson
union all
select id, 'Which of the following are examples of availability controls? (Select two.)', 'multi', '[{"id": "a", "text": "Offsite backups"}, {"id": "b", "text": "Disaster recovery planning"}, {"id": "c", "text": "Data masking"}, {"id": "d", "text": "Need-to-know access restrictions"}]'::jsonb, '["a", "b"]'::jsonb, 'Backups and disaster recovery planning both support continued access to systems and data. Data masking and need-to-know restrictions protect confidentiality.' from new_lesson
union all
select id, 'What is the best definition of ''least privilege''?', 'single', '[{"id": "a", "text": "Giving users the minimum access necessary to perform their job function"}, {"id": "b", "text": "Requiring two forms of authentication for all system access"}, {"id": "c", "text": "Encrypting all data both at rest and in transit"}, {"id": "d", "text": "Logging every action a user takes on a system"}]'::jsonb, '["a"]'::jsonb, 'Least privilege means granting only the access required to do the job, minimizing exposure if an account is compromised.' from new_lesson
union all
select id, 'A system administrator can prove, via signed and timestamped logs, exactly which engineer deployed a specific configuration change. This capability primarily supports which property?', 'single', '[{"id": "a", "text": "Non-repudiation"}, {"id": "b", "text": "Availability"}, {"id": "c", "text": "Confidentiality"}, {"id": "d", "text": "Integrity"}]'::jsonb, '["a"]'::jsonb, 'Being able to conclusively attribute an action to a specific individual, such that they can''t deny it, is the definition of non-repudiation.' from new_lesson
union all
select id, 'Which scenario represents an integrity violation rather than a confidentiality violation?', 'single', '[{"id": "a", "text": "An unauthorized user views an employee''s salary record"}, {"id": "b", "text": "An attacker modifies a bank account balance in a database"}, {"id": "c", "text": "A laptop containing customer data is stolen"}, {"id": "d", "text": "An employee emails a confidential report to the wrong recipient"}]'::jsonb, '["b"]'::jsonb, 'Modifying data without authorization is an integrity violation. The other options all involve unauthorized disclosure, which is confidentiality.' from new_lesson;

-- Lesson 2: Security Governance: Policies, Standards, Procedures, and Guidelines
delete from progress where lesson_id in (select id from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'Security Governance: Policies, Standards, Procedures, and Guidelines');
delete from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'Security Governance: Policies, Standards, Procedures, and Guidelines';
with new_lesson as (
  insert into lessons (course_id, section_id, title, order_index, estimated_minutes, content_blocks)
  select c.id, s.id, 'Security Governance: Policies, Standards, Procedures, and Guidelines', 2, 9, '[{"type": "heading", "text": "How Security Documentation Fits Together"}, {"type": "paragraph", "text": "Security governance runs top-down: a broad policy sets direction, and standards, procedures, baselines, and guidelines each translate that direction into something people and systems can actually follow. Knowing which is which (and which are mandatory versus advisory) is a heavily tested area."}, {"type": "key_term", "term": "Policy", "definition": "A high-level statement of management''s goals and expectations for protecting organizational assets. Approved at the executive/board level. Mandatory."}, {"type": "key_term", "term": "Standard", "definition": "A specific, mandatory technical requirement that supports a policy - for example, naming a required firewall vendor or mandating a specific encryption algorithm. Mandatory."}, {"type": "key_term", "term": "Procedure", "definition": "Step-by-step instructions for carrying out a standard - the exact clicks and commands to configure something correctly. Mandatory."}, {"type": "key_term", "term": "Baseline", "definition": "The minimum acceptable security configuration for a system or process, used as a reference point for compliance. Mandatory."}, {"type": "key_term", "term": "Guideline", "definition": "A recommended, flexible best practice - not mandatory, and not something an auditor can cite you for failing to follow."}, {"type": "list", "style": "numbered", "items": ["Policy - sets the goal (\"all endpoints must run anti-malware protection\")", "Standard - names the specific tool/technology (\"approved anti-malware product is Vendor X\")", "Baseline - sets the minimum configuration (\"real-time scanning must be enabled\")", "Procedure - gives the exact installation/configuration steps", "Guideline - offers optional best-practice suggestions (\"consider enabling heuristic scanning\")"]}, {"type": "callout", "variant": "tip", "text": "Exam tip: the fastest way to spot the odd one out is mandatory vs. advisory. Policies, standards, procedures, and baselines are all mandatory. Guidelines are the only one that''s optional."}]'::jsonb
  from courses c
  join sections s on s.course_id = c.id and s.slug = 'security-and-risk-management'
  where c.slug = 'cissp'
  returning id
)
insert into questions (lesson_id, question_text, question_type, choices, correct_choice_ids, explanation)
select id, 'Which of these governance documents is the ONLY one that is advisory rather than mandatory?', 'single', '[{"id": "a", "text": "Standard"}, {"id": "b", "text": "Guideline"}, {"id": "c", "text": "Baseline"}, {"id": "d", "text": "Procedure"}]'::jsonb, '["b"]'::jsonb, 'Guidelines are recommended best practices; policies, standards, procedures, and baselines are all mandatory.' from new_lesson
union all
select id, 'A document stating ''all remote access must use multi-factor authentication'' and signed off by the board is best classified as a:', 'single', '[{"id": "a", "text": "Procedure"}, {"id": "b", "text": "Guideline"}, {"id": "c", "text": "Policy"}, {"id": "d", "text": "Baseline"}]'::jsonb, '["c"]'::jsonb, 'A high-level, board-approved statement of intent is a policy - the top of the governance hierarchy.' from new_lesson
union all
select id, 'Which document specifies that the organization''s approved MFA solution is a named vendor''s authenticator app?', 'single', '[{"id": "a", "text": "Policy"}, {"id": "b", "text": "Standard"}, {"id": "c", "text": "Guideline"}, {"id": "d", "text": "Baseline"}]'::jsonb, '["b"]'::jsonb, 'Standards name the specific technology or product used to satisfy a policy.' from new_lesson
union all
select id, 'Which document contains the exact click-by-click steps a help desk technician follows to enroll a user in MFA?', 'single', '[{"id": "a", "text": "Standard"}, {"id": "b", "text": "Baseline"}, {"id": "c", "text": "Procedure"}, {"id": "d", "text": "Guideline"}]'::jsonb, '["c"]'::jsonb, 'Procedures are the step-by-step operational instructions for carrying out a standard.' from new_lesson
union all
select id, 'Which of the following are mandatory governance documents? (Select two.)', 'multi', '[{"id": "a", "text": "Guideline"}, {"id": "b", "text": "Baseline"}, {"id": "c", "text": "Standard"}, {"id": "d", "text": "Suggested best practice memo"}]'::jsonb, '["b", "c"]'::jsonb, 'Baselines and standards are both mandatory. Guidelines and informal best-practice memos are advisory.' from new_lesson
union all
select id, 'A minimum required hardening configuration that every server image must meet before deployment is best described as a:', 'single', '[{"id": "a", "text": "Guideline"}, {"id": "b", "text": "Baseline"}, {"id": "c", "text": "Policy"}, {"id": "d", "text": "Procedure"}]'::jsonb, '["b"]'::jsonb, 'A baseline is the minimum acceptable security configuration, used as a reference point for compliance checks.' from new_lesson
union all
select id, 'Who typically has approval authority for organization-wide security policies?', 'single', '[{"id": "a", "text": "Individual system administrators"}, {"id": "b", "text": "Help desk technicians"}, {"id": "c", "text": "Senior/executive management or the board"}, {"id": "d", "text": "The vendor providing the security tool"}]'::jsonb, '["c"]'::jsonb, 'Policies carry organizational authority and are approved at the executive/board level, distinguishing them from lower-level documents.' from new_lesson
union all
select id, 'A team recommends (but does not require) enabling an optional heuristic scanning feature in the antivirus configuration. This recommendation is best classified as a:', 'single', '[{"id": "a", "text": "Standard"}, {"id": "b", "text": "Guideline"}, {"id": "c", "text": "Policy"}, {"id": "d", "text": "Baseline"}]'::jsonb, '["b"]'::jsonb, 'Optional, flexible recommendations are guidelines - the only non-mandatory document in the hierarchy.' from new_lesson
union all
select id, 'Which of the following correctly orders the governance hierarchy from broadest/highest authority to most specific/operational?', 'single', '[{"id": "a", "text": "Procedure -> Standard -> Policy -> Baseline"}, {"id": "b", "text": "Policy -> Standard/Baseline -> Procedure"}, {"id": "c", "text": "Guideline -> Policy -> Standard -> Procedure"}, {"id": "d", "text": "Baseline -> Policy -> Procedure -> Standard"}]'::jsonb, '["b"]'::jsonb, 'Policy sets the goal at the top; standards and baselines define specific technical requirements; procedures give the operational steps to implement them.' from new_lesson
union all
select id, 'An auditor cites an organization for failing to meet a documented requirement. Which of the following could NOT be the source of that finding?', 'single', '[{"id": "a", "text": "Policy"}, {"id": "b", "text": "Standard"}, {"id": "c", "text": "Guideline"}, {"id": "d", "text": "Baseline"}]'::jsonb, '["c"]'::jsonb, 'Guidelines are advisory, not mandatory, so failing to follow one is not a compliance violation an auditor can cite.' from new_lesson;

-- Lesson 3: Risk Management Fundamentals
delete from progress where lesson_id in (select id from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'Risk Management Fundamentals');
delete from lessons where course_id = (select id from courses where slug = 'cissp') and section_id = (select id from sections where course_id = (select id from courses where slug = 'cissp') and slug = 'security-and-risk-management') and title = 'Risk Management Fundamentals';
with new_lesson as (
  insert into lessons (course_id, section_id, title, order_index, estimated_minutes, content_blocks)
  select c.id, s.id, 'Risk Management Fundamentals', 3, 9, '[{"type": "heading", "text": "Identifying, Assessing, and Treating Risk"}, {"type": "paragraph", "text": "Risk management is the process of identifying, analyzing, and prioritizing risk, then applying resources to reduce its probability or impact to an acceptable level. Almost every other topic in this course exists to manage some category of risk."}, {"type": "key_term", "term": "Asset", "definition": "Anything of value to the organization that needs protecting - data, systems, people, reputation."}, {"type": "key_term", "term": "Threat", "definition": "Any potential danger that could exploit a vulnerability and cause harm to an asset."}, {"type": "key_term", "term": "Vulnerability", "definition": "A weakness that a threat can exploit - an unpatched system, a weak password policy, an unlocked server room."}, {"type": "key_term", "term": "Risk", "definition": "The likelihood of a threat exploiting a vulnerability, combined with the resulting impact. Risk exists only where a threat and a matching vulnerability both exist."}, {"type": "paragraph", "text": "Once a risk is identified, an organization has four options for treating it."}, {"type": "list", "style": "bullet", "items": ["Avoid - stop doing the activity that creates the risk entirely.", "Mitigate - apply controls to reduce likelihood or impact to an acceptable level.", "Transfer - shift the risk to someone else, typically via insurance or a contract.", "Accept - formally acknowledge the risk and take no further action, usually because the cost of treatment exceeds the potential loss."]}, {"type": "callout", "variant": "info", "text": "Quantitative risk analysis puts a dollar figure on risk: Single Loss Expectancy (SLE) is the cost of one occurrence; Annualized Rate of Occurrence (ARO) is how often it''s expected per year; Annualized Loss Expectancy (ALE) = SLE x ARO. If a $50,000 loss (SLE) is expected once every 4 years (ARO = 0.25), ALE = $12,500/year - that figure helps justify how much to spend on a control."}]'::jsonb
  from courses c
  join sections s on s.course_id = c.id and s.slug = 'security-and-risk-management'
  where c.slug = 'cissp'
  returning id
)
insert into questions (lesson_id, question_text, question_type, choices, correct_choice_ids, explanation)
select id, 'A company decides to stop accepting a certain type of payment entirely because the fraud risk is too high to manage. Which risk treatment strategy is this?', 'single', '[{"id": "a", "text": "Mitigate"}, {"id": "b", "text": "Transfer"}, {"id": "c", "text": "Avoid"}, {"id": "d", "text": "Accept"}]'::jsonb, '["c"]'::jsonb, 'Eliminating the activity that creates the risk entirely is risk avoidance.' from new_lesson
union all
select id, 'A company purchases cyber liability insurance to cover the financial impact of a potential data breach. Which risk treatment strategy is this?', 'single', '[{"id": "a", "text": "Avoid"}, {"id": "b", "text": "Transfer"}, {"id": "c", "text": "Mitigate"}, {"id": "d", "text": "Accept"}]'::jsonb, '["b"]'::jsonb, 'Shifting the financial impact of a risk to a third party, such as an insurer, is risk transfer.' from new_lesson
union all
select id, 'A single security incident is expected to cost $40,000, and history shows it happens about once every 5 years. What is the Annualized Loss Expectancy (ALE)?', 'single', '[{"id": "a", "text": "$2,000"}, {"id": "b", "text": "$8,000"}, {"id": "c", "text": "$40,000"}, {"id": "d", "text": "$200,000"}]'::jsonb, '["b"]'::jsonb, 'ARO = 1/5 = 0.2. ALE = SLE x ARO = $40,000 x 0.2 = $8,000.' from new_lesson
union all
select id, 'An unpatched web server is an example of which risk component?', 'single', '[{"id": "a", "text": "Threat"}, {"id": "b", "text": "Asset"}, {"id": "c", "text": "Vulnerability"}, {"id": "d", "text": "Risk treatment"}]'::jsonb, '["c"]'::jsonb, 'An unpatched system is a weakness that could be exploited - the definition of a vulnerability.' from new_lesson
union all
select id, 'Which of the following are valid risk treatment strategies? (Select two.)', 'multi', '[{"id": "a", "text": "Mitigate"}, {"id": "b", "text": "Ignore"}, {"id": "c", "text": "Accept"}, {"id": "d", "text": "Escalate"}]'::jsonb, '["a", "c"]'::jsonb, 'The four recognized risk treatment strategies are avoid, mitigate, transfer, and accept. ''Ignore'' and ''escalate'' are not formal treatment categories.' from new_lesson
union all
select id, 'Management reviews a low-impact, low-likelihood risk and decides the cost of any control would exceed the potential loss, so no action is taken. This is:', 'single', '[{"id": "a", "text": "Risk avoidance"}, {"id": "b", "text": "Risk transfer"}, {"id": "c", "text": "Risk mitigation"}, {"id": "d", "text": "Risk acceptance"}]'::jsonb, '["d"]'::jsonb, 'Formally acknowledging a risk and taking no further action, because treatment costs more than the potential loss, is risk acceptance.' from new_lesson
union all
select id, 'A company implements multi-factor authentication to reduce the likelihood of a successful account takeover. Which risk treatment strategy is this?', 'single', '[{"id": "a", "text": "Mitigate"}, {"id": "b", "text": "Avoid"}, {"id": "c", "text": "Transfer"}, {"id": "d", "text": "Accept"}]'::jsonb, '["a"]'::jsonb, 'Applying a control to reduce the likelihood or impact of a risk, without eliminating the underlying activity, is mitigation.' from new_lesson
union all
select id, 'If Single Loss Expectancy (SLE) is $10,000 and Annualized Rate of Occurrence (ARO) is 2 (expected twice per year), what is the ALE?', 'single', '[{"id": "a", "text": "$5,000"}, {"id": "b", "text": "$10,000"}, {"id": "c", "text": "$20,000"}, {"id": "d", "text": "$2,000"}]'::jsonb, '["c"]'::jsonb, 'ALE = SLE x ARO = $10,000 x 2 = $20,000.' from new_lesson
union all
select id, 'A phishing group actively targeting companies in your industry is best described as a:', 'single', '[{"id": "a", "text": "Vulnerability"}, {"id": "b", "text": "Threat"}, {"id": "c", "text": "Risk treatment"}, {"id": "d", "text": "Baseline"}]'::jsonb, '["b"]'::jsonb, 'A potential source of harm - here, an active attacker group - is a threat, distinct from the vulnerability it might exploit.' from new_lesson
union all
select id, 'Which statement correctly relates threat, vulnerability, and risk?', 'single', '[{"id": "a", "text": "Risk exists only where a threat and a matching vulnerability both exist"}, {"id": "b", "text": "A vulnerability is only relevant if there is no applicable threat"}, {"id": "c", "text": "Threats and vulnerabilities are interchangeable terms"}, {"id": "d", "text": "Risk is eliminated automatically once a vulnerability is identified"}]'::jsonb, '["a"]'::jsonb, 'Risk is the intersection of a threat that can exploit a vulnerability. Neither alone constitutes risk.' from new_lesson;
