-- Restructure Domain 1 lesson content: group thin/sparse slides together and add
-- inline **bold** emphasis on key terms so the lesson player has denser, clearer slides.
-- Safe to re-run - each statement is a full UPDATE keyed by lesson title within the cissp course.

update lessons set content_blocks = '[{"type": "heading", "text": "Why the CIA Triad Matters"}, {"type": "paragraph", "text": "Nearly every security control you''ll ever evaluate exists to protect one (or more) of three properties: **confidentiality**, **integrity**, and **availability**. When a CISSP exam question asks \"what security principle was violated,\" it''s almost always asking you to identify which of these three."}, {"type": "key_term", "term": "Confidentiality", "definition": "Preventing unauthorized disclosure of information. Enforced through principles like need-to-know and least privilege, and controls like encryption and role-based access."}, {"type": "key_term", "term": "Integrity", "definition": "Protecting data and systems from unauthorized modification, ensuring information stays accurate and trustworthy. Enforced through controls like change management, hashing, and digital signatures."}, {"type": "key_term", "term": "Availability", "definition": "Ensuring authorized users can access systems and data when they need to. Enforced through controls like redundancy, backups, and disaster recovery planning."}, {"type": "group", "heading": "Beyond the Core Three", "blocks": [{"type": "paragraph", "text": "Two related properties extend the triad and show up regularly on the exam: **authenticity** (proving an asset or identity is genuine) and **non-repudiation** (preventing someone from credibly denying an action they took, typically via audit logs and digital signatures)."}, {"type": "list", "style": "bullet", "items": ["A stolen laptop full of unencrypted customer records is a **confidentiality** failure.", "An attacker altering financial transaction data in transit is an **integrity** failure.", "A DDoS attack that takes a website offline is an **availability** failure.", "A forged email claiming to be from the CEO is an **authenticity** failure.", "A user denying they approved a wire transfer that logs show they approved is a **non-repudiation** failure."]}]}, {"type": "callout", "variant": "tip", "text": "Exam tip: scenario questions describe an incident and ask which principle was violated. Read for the *effect* of the attack (data exposed? data changed? system down?), not the attack method itself."}]'::jsonb
where course_id = (select id from courses where slug = 'cissp')
and title = 'The CIA Triad';

update lessons set content_blocks = '[{"type": "heading", "text": "How Security Documentation Fits Together"}, {"type": "paragraph", "text": "Security governance runs top-down: a broad **policy** sets direction, and **standards**, **procedures**, **baselines**, and **guidelines** each translate that direction into something people and systems can actually follow. Knowing which is which (and which are mandatory versus advisory) is a heavily tested area."}, {"type": "key_term", "term": "Policy", "definition": "A high-level statement of management''s goals and expectations for protecting organizational assets. Approved at the executive/board level. Mandatory."}, {"type": "key_term", "term": "Standard", "definition": "A specific, mandatory technical requirement that supports a policy - for example, naming a required firewall vendor or mandating a specific encryption algorithm. Mandatory."}, {"type": "key_term", "term": "Procedure", "definition": "Step-by-step instructions for carrying out a standard - the exact clicks and commands to configure something correctly. Mandatory."}, {"type": "key_term", "term": "Baseline", "definition": "The minimum acceptable security configuration for a system or process, used as a reference point for compliance. Mandatory."}, {"type": "key_term", "term": "Guideline", "definition": "A recommended, flexible best practice - not mandatory, and not something an auditor can cite you for failing to follow."}, {"type": "group", "heading": "Putting It in Order", "blocks": [{"type": "list", "style": "numbered", "items": ["**Policy** - sets the goal (\"all endpoints must run anti-malware protection\")", "**Standard** - names the specific tool/technology (\"approved anti-malware product is Vendor X\")", "**Baseline** - sets the minimum configuration (\"real-time scanning must be enabled\")", "**Procedure** - gives the exact installation/configuration steps", "**Guideline** - offers optional best-practice suggestions (\"consider enabling heuristic scanning\")"]}, {"type": "callout", "variant": "tip", "text": "Exam tip: the fastest way to spot the odd one out is mandatory vs. advisory. Policies, standards, procedures, and baselines are all mandatory. **Guidelines are the only one that''s optional.**"}]}]'::jsonb
where course_id = (select id from courses where slug = 'cissp')
and title = 'Security Governance: Policies, Standards, Procedures, and Guidelines';

update lessons set content_blocks = '[{"type": "heading", "text": "Identifying, Assessing, and Treating Risk"}, {"type": "paragraph", "text": "Risk management is the process of identifying, analyzing, and prioritizing risk, then applying resources to reduce its probability or impact to an acceptable level. Almost every other topic in this course exists to manage some category of risk."}, {"type": "key_term", "term": "Asset", "definition": "Anything of value to the organization that needs protecting - data, systems, people, reputation."}, {"type": "key_term", "term": "Threat", "definition": "Any potential danger that could exploit a vulnerability and cause harm to an asset."}, {"type": "key_term", "term": "Vulnerability", "definition": "A weakness that a threat can exploit - an unpatched system, a weak password policy, an unlocked server room."}, {"type": "key_term", "term": "Risk", "definition": "The likelihood of a threat exploiting a vulnerability, combined with the resulting impact. Risk exists only where a threat and a matching vulnerability both exist."}, {"type": "group", "heading": "The Four Ways to Treat a Risk", "blocks": [{"type": "paragraph", "text": "Once a risk is identified, an organization has four options for treating it."}, {"type": "list", "style": "bullet", "items": ["**Avoid** - stop doing the activity that creates the risk entirely.", "**Mitigate** - apply controls to reduce likelihood or impact to an acceptable level.", "**Transfer** - shift the risk to someone else, typically via insurance or a contract.", "**Accept** - formally acknowledge the risk and take no further action, usually because the cost of treatment exceeds the potential loss."]}]}, {"type": "callout", "variant": "info", "text": "Quantitative risk analysis puts a dollar figure on risk: **Single Loss Expectancy (SLE)** is the cost of one occurrence; **Annualized Rate of Occurrence (ARO)** is how often it''s expected per year; **Annualized Loss Expectancy (ALE) = SLE x ARO**. If a $50,000 loss (SLE) is expected once every 4 years (ARO = 0.25), ALE = $12,500/year - that figure helps justify how much to spend on a control."}]'::jsonb
where course_id = (select id from courses where slug = 'cissp')
and title = 'Risk Management Fundamentals';
